# Generated by Django 5.2.4 on 2025-07-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inward_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
