# Generated by Django 5.2.4 on 2025-07-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inventory_inward_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PO_RAISED', 'PO Raised'), ('PO_APPROVED', 'PO Approved'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('INWARD_DONE', 'Added to Inventory / Inward Done')], default='PO_RAISED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vendor')),
            ],
        ),
    ]
