# Generated by Django 5.2.4 on 2025-07-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PO_RAISED', 'PO Raised'), ('PO_APPROVED', 'PO Approved'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('INWARD_DONE', 'Inward Done')], default='PO_RAISED', max_length=20),
        ),
    ]
