# Generated by Django 5.2.4 on 2025-07-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Product ID'),
        ),
    ]
