# Generated by Django 5.2.4 on 2025-07-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='name', max_length=20, unique=True, verbose_name='Product ID'),
            preserve_default=False,
        ),
    ]
