# Generated by Django 5.2.4 on 2025-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vendor_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(default='n/a', max_length=20, unique=True, verbose_name='Vendor ID'),
            preserve_default=False,
        ),
    ]
