# Generated by Django 5.2.4 on 2025-07-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_vendor_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='permissions',
        ),
    ]
