# Generated by Django 5.2.4 on 2025-07-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('INWARD_REQUESTED', 'Inward Requested'), ('INWARD_APPROVED', 'Inward Approved'), ('INWARD_DONE', 'Inward Done')], default='INWARD_REQUESTED', max_length=20),
        ),
    ]
