# Generated by Django 5.2.4 on 2025-07-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('INWARD_REQUESTED', 'Requested'), ('INWARD_APPROVED', 'Approved'), ('INWARD_REJECTED', 'Rejected'), ('INWARD_COMPLETED', 'Completed')], default='INWARD_REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PO_RAISED', 'Raised'), ('PO_APPROVED', 'Approved'), ('PO_REJECTED', 'Rejected'), ('PO_SHIPPED', 'Shipped'), ('PO_DELIVERED', 'Delivered'), ('INWARD_REQUESTED', 'Inward Requested')], default='PO_RAISED', max_length=20),
        ),
    ]
