# Generated by Django 5.2.4 on 2025-07-20 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_purchaseorder_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inward_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
