# Generated by Django 5.2.4 on 2025-07-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_inventory_inward_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
