# Generated by Django 5.2.4 on 2025-07-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_userprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PO_RAISED', 'Raised'), ('PO_APPROVED', 'Approved'), ('PO_REJECTED', 'Rejected'), ('PO_SHIPPED', 'Shipped'), ('PO_DELIVERED', 'Delivered'), ('INWARD_REQUESTED', 'Inward')], default='PO_RAISED', max_length=20),
        ),
    ]
