# Generated by Django 5.2.4 on 2025-07-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_inventory_approval_status_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='order',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER_RAISED', 'Raised'), ('ORDER_APPROVED', 'Approved'), ('ORDER_REJECTED', 'Rejected'), ('ORDER_SHIPPED', 'Shipped'), ('ORDER_DELIVERED', 'Delivered'), ('ORDER_RETURNED', 'Returned')], default='ORDER_RAISED', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('sourcing_team', 'Sourcing Team'), ('sourcing_manager', 'Sourcing Manager'), ('sales_team', 'Sales Team'), ('sales_manager', 'Sales Manager'), ('logistics_team', 'Logistics Team'), ('logistics_manager', 'Logistics Manager'), ('team_lead', 'Team Leader')], default='customer_team', max_length=30),
        ),
    ]
